# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47978d2f005644535c0f98de68c93c29541ef81bbcf08ccef5bf0e162ff0b62c6b07ea52d7c6e8d25b0bfa89400be388a29e7b950cccc9314f8fa8730f67b223

test:
  secret_key_base: 40e856cd6a9532cdcdc0fe9e6764aa7519133448c2eec7383c056715afeb93fa8218d04069e21acd10dde4ebd37b3dde3579bb6ff7666988e27b797236e79b95

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
